shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('order.urls')),
    path('', include('shop_main_app.urls')),
    path('', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int, label='Количество')
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """добавление товара в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    """удаление товара из корзины"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """просмотр содержимого корзины"""
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/cart.html', {'cart': cart, 'categories': Category.objects.all()})

shop/cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block maincontent %}
{% load static %}
<link type="text/css" href="{% static 'cart/css/cart.css' %}" rel="stylesheet">


<div class="ordercontent">
    <div class="orderconentborder">
        <div class="itemsinbasketh1">
    <h1 class="headtext-center">ТОВАРЫ В КОРЗИНЕ</h1>
</div>
        {% for item in cart %}
        {% with product=item.product %}
    <div class="iteminbasket">
        <div class="iteminbasketblock name">
            <h2 class="itembasketnameh2">{{ product.name }}</h2>
        </div>
        <div class="iteminbasketblock image">
            <img class="imgimgimg" src="{{ product.image.url }}" alt="">
        </div>
        <div class="iteminbasketblock price">
            <h2 class="itembasketpriceh2">{{ item.price }} BYN</h2>
        </div>
        <div class="iteminbasketblock quantity">
            <form class="formquantitychange" action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <h5>шт.</h5>
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
        </div>
        <div class="iteminbasketblock remove">
            <a href="{% url 'cart:cart_remove' product.id %}"><h3>удалить</h3></a>
        </div>
        <div class="iteminbasketblock totalprice">
            <h2 class="num">{{ item.total_price }} BYN</h2>
        </div>

    </div>
{% endwith %}
      {% endfor %}
        <div class="cartbottom">
        <div class="totalprice">
            <h1>Всего {{ cart.get_total_price }} BYN</h1>
        </div>
        <div class="orderbotton">
            <a href="{% url 'order' %}" class="button10">Оформить заказ</a>
        </div>
            </div>

</div>
</div>
</div>
</div>
{% endblock %}
{% block promotion %}
{% endblock %}